[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.3"
png = "0.17.7"
rand = "0.8.5"
rayon = "1.6.1"

#[profile.release]
#lto = true
#codegen-units = 1
#panic = "abort"
