[package]
name = "gpu_raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.15.1"
pollster = "0.3.0"
futures-intrusive = "0.5.0"
png = "0.17.7"
